version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5432:5432"

  clean architecture:
    build: .
    depends_on:
      - db
    ports:
      - "9030:9030" # REST API
      - "9031:9031" # GraphQL
      - "50051:50051" # GRPC