version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: social
      MYSQL_DATABASE: social
    ports:
      - "9031:9031"
    volumes:
      - db_data:/var/lib/mysql

  rest-api:
    build: .
    depends_on:
      - db
    ports:
      - "9030:9030"

  grpc-api:
    build: .
    depends_on:
      - db
    ports:
      - "50051:50051"

  graphql-api:
    build: .
    depends_on:
      - db
    ports:
      - "9032:9032"

volumes:
  db_data: